/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/portrait.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.beanie_low_RetopoFlow017.geometry}
        material={materials['Material.002']}
        position={[0, 0.94, -0.15]}
        rotation={[1.45, 0, 0]}
        scale={[0.77, 0.74, 0.83]}
      />
      <mesh geometry={nodes.FaceBuilderHead.geometry} material={materials.FaceTexture} />
      <mesh geometry={nodes.Mesh.geometry} material={materials.Mustache} />
      <mesh
        geometry={nodes.Torus.geometry}
        material={materials['Material.005']}
        position={[0, -0.07, 1.23]}
        rotation={[1.56, 0, 0.02]}
        scale={[0.06, 0.06, 0.06]}
      />
    </group>
  )
}

useGLTF.preload('/portrait.gltf')
