// Personal website and portfolio //
// 2022                           //
// Built by Mark Lisanti          //
// https://github.com/marklasagne //

// GLTF model Auto-generated by: https://github.com/pmndrs/gltfjsx

import React, { useRef } from 'react'
import { useFrame, useThree } from '@react-three/fiber'
import { useGLTF, } from '@react-three/drei'

export default function Model({ ...props }) {
  const { viewport } = useThree()
  const { nodes, materials } = useGLTF('/portrait.gltf')
  const group = useRef()
  const eyes = useRef()
  let xMiddle = viewport.width / 2
  let yMiddle = viewport.height / 2

  useFrame(({ mouse }) => {
    const x = (mouse.x * xMiddle) / 30
    const y = (mouse.y * yMiddle) / 30
    group.current.rotation.set(-y, x, 0)
    eyes.current.rotation.set(-y / 4, x / 4, 0)
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh receiveShadow
        geometry={nodes.beanie_low_RetopoFlow017.geometry}
        material={materials['Material.002']}
        position={[0, 0.94, -0.15]}
        rotation={[1.45, 0, 0]}
        scale={[0.77, 0.74, 0.83]}
      />
      <group ref={eyes}>
        <mesh receiveShadow
          geometry={nodes.uploads_files_172137_eye.geometry}
          material={materials['Default OBJ']}
          position={[0.3, 0.35, 0.89]}
          rotation={[1.68, 0.51, -0.23]}
          scale={[0.26, 0.3, 0.25]}
        />
        <mesh receiveShadow
          geometry={nodes.uploads_files_172137_eye001.geometry}
          material={materials['Default OBJ.004']}
          position={[-0.28, 0.36, 0.89]}
          rotation={[1.44, 0.51, 0.27]}
          scale={[0.26, 0.3, 0.25]}
        />
      </group>
      <mesh receiveShadow geometry={nodes.FaceBuilderHead.geometry} material={materials.FaceTexture} />
      <mesh receiveShadow geometry={nodes.Mesh.geometry} material={materials.Mustache} />
      <mesh receiveShadow
        geometry={nodes.Torus.geometry}
        material={materials['Material.005']}
        position={[0, -0.07, 1.23]}
        rotation={[1.56, 0, 0.02]}
        scale={[0.06, 0.06, 0.06]}
      />
    </group>
  )
}

useGLTF.preload('/portrait.gltf')
